name: Tabi API Deployment

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    environment: deployment
    runs-on: ubuntu-latest

    steps:
      - name: Configure docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:$GITHUB_SHA ./Tabi

      - name: Publish to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:$GITHUB_SHA
